Merge some of Yu-Hsiang's improvements to the nrsnrs submission script for summit
* control over queue
* overwrite session file to match the provided parameters
* simplify checking existance of case files

diff --git a/scripts/nrsnrsqsub_summit b/scripts/nrsnrsqsub_summit
--- a/scripts/nrsnrsqsub_summit
+++ b/scripts/nrsnrsqsub_summit
@@ -1,11 +1,10 @@
 #/bin/bash
 
 : ${PROJ_ID:=""}
+: ${QUEUE:="batch"} # batch, batch-hm, debug
 
-if [ -z "$PROJ_ID" ]; then
-  echo "ERROR: PROJ_ID is empty"
-  exit 1
-fi
+: ${NEKRS_HOME:="$HOME/.local/nekrs"}
+: ${OCCA_CACHE_DIR:="$PWD/.cache/occa"}
 
 if [ $# -ne 7 ]; then
   echo "usage: [PROJ_ID] [CPUONLY=1] $0 <sess> <case1> <case2> <number of compute nodes> <procsA> <procsB> <hh:mm>"
@@ -13,8 +12,15 @@ if [ $# -ne 7 ]; then
   exit 0
 fi
 
-: ${NEKRS_HOME:="$HOME/.local/nekrs"}
-: ${OCCA_CACHE_DIR:="$PWD/.cache/occa"}
+if [ -z "$PROJ_ID" ]; then
+  echo "ERROR: PROJ_ID is empty"
+  exit 1
+fi
+if [ -z "$QUEUE" ]; then
+  echo "ERROR: QUEUE is empty"
+  exit 1
+fi
+
 NVME_HOME="/mnt/bb/$USER/"
 
 # temporary load xl modules for OLCF_XLC_ROOT
@@ -30,8 +36,8 @@ export OCCA_CACHE_DIR
 export NEKRS_HYPRE_NUM_THREADS=1
 export NEKRS_GPU_MPI=1
 if [ $CPUONLY -eq 1 ]; then
-  export OCCA_CXX="$XL_HOME/bin/xlc++" 
-  export OCCA_CXXFLAGS="-O3 -qarch=pwr9 -qhot -DUSE_OCCA_MEM_BYTE_ALIGN=64" 
+  export OCCA_CXX="$XL_HOME/bin/xlc++"
+  export OCCA_CXXFLAGS="-O3 -qarch=pwr9 -qhot -DUSE_OCCA_MEM_BYTE_ALIGN=64"
   export OCCA_LDFLAGS="$XL_HOME/lib/libibmc++.a"
 fi
 
@@ -76,52 +82,41 @@ if [ $CPUONLY -eq 1 ]; then
   backend=CPU
   let nn=2*$nodes
   let ntasks=$nn*$cores_per_socket
-fi 
+fi
+
+let nn_chk=$procsA+$procsB
+if [[ $nn_chk -ne $nn ]]; then
+  echo "#mpi: "$procsA"+"$procsB" does not match "$nodes" nodes!"
+  exit 1
+fi
 
 if [ ! -f $bin ]; then
   echo "Cannot find" $bin
   exit 1
 fi
 
-if [ ! -f $caseA/$caseA.par ]; then
-  echo "Cannot find" $caseA.par
+if [ ! -d $caseA ]; then
+  echo "Cannot find folder" $caseA
   exit 1
 fi
 
-if [ ! -f $caseA/$caseA.udf ]; then
-  echo "Cannot find" $caseA.udf
+if [ ! -d $caseB ]; then
+  echo "Cannot find folder" $caseB
   exit 1
 fi
 
-if [ ! -f $caseA/$caseA.oudf ]; then
-  echo "Cannot find" $caseA.oudf
-  exit 1
-fi
+list=($caseA/$caseA.par $caseA/$caseA.udf $caseA/$caseA.oudf $caseA/$caseA.re2\
+      $caseB/$caseB.par $caseB/$caseB.udf $caseB/$caseB.oudf $caseB/$caseB.re2)
+for f in ${list[@]}; do
+  if [ ! -f $f ]; then
+    echo "Cannot find" $f
+    exit 1
+  fi
+done
 
-if [ ! -f $caseA/$caseA.re2 ]; then
-  echo "Cannot find" $caseA.re2
-  exit 1
-fi
-
-if [ ! -f $caseB/$caseB.par ]; then
-  echo "Cannot find" $caseB.par
-  exit 1
-fi
-
-if [ ! -f $caseB/$caseB.udf ]; then
-  echo "Cannot find" $caseB.udf
-  exit 1
-fi
-
-if [ ! -f $caseB/$caseB.oudf ]; then
-  echo "Cannot find" $caseB.oudf
-  exit 1
-fi
-
-if [ ! -f $caseB/$caseB.re2 ]; then
-  echo "Cannot find" $caseB.re2
-  exit 1
-fi
+# NekNek sess file
+echo $caseA"/"$caseA":"$procsA";" >  ${sess}
+echo $caseB"/"$caseB":"$procsB";" >> ${sess}
 
 mkdir -p $OCCA_CACHE_DIR 2>/dev/null
 
@@ -153,6 +148,6 @@ else
   jsrun="jsrun --smpiargs='-gpu' -X 1 -n$nn -r$gpu_per_node -a1 -c2 -g1 -b rs -d packed $bin --setup ${sess} --backend $backend --device-id 0"
 fi
 
-cmd="bsub -nnodes $nodes -alloc_flags NVME -W $time -P $PROJ_ID -J nekRS_${sess} '${IO_STEPS} ${jsrun}; ${POST_STEPS}'"
+cmd="bsub -q $QUEUE -nnodes $nodes -alloc_flags NVME -W $time -P $PROJ_ID -J nekRS_${sess} '${IO_STEPS} ${jsrun}; ${POST_STEPS}'"
 echo $cmd
 $cmd
