Import next changes SHA[1e48151f, 10bcc05e]

diff --git a/scripts/nrsqsub_frontier b/scripts/nrsqsub_frontier
--- a/scripts/nrsqsub_frontier
+++ b/scripts/nrsqsub_frontier
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 : ${PROJ_ID:=""}
-: ${QUEUE:=""}
+: ${QUEUE:="batch"}
 : ${NEKRS_HOME:="$HOME/.local/nekrs"}
 : ${NEKRS_CACHE_BCAST:=1}
 : ${NEKRS_SKIP_BUILD_ONLY:=0}
@@ -27,12 +27,18 @@ bin=${NEKRS_HOME}/bin/nekrs
 case=$1
 nodes=$2
 gpu_per_node=8
-cores_per_socket=7
+cores_per_numa=7
 let nn=$nodes*$gpu_per_node
 let ntasks=nn
 time=$3
 backend=HIP
 
+time_fmt=`echo $time|tr ":" " "|awk '{print NF}'`
+if [ "$time_fmt" -ne "3" ]; then
+  echo "Warning: time is not in the format <hh:mm:ss>"
+  echo $time
+  exit 1
+fi
 
 if [ ! -f $bin ]; then
   echo "Cannot find" $bin
@@ -54,19 +60,16 @@ if [ ! -f $case.re2 ]; then
   exit 1
 fi
 
-
-# romio setup
-export ROMIO_HINTS="$(pwd)/.romio_hint"
-if [ ! -f "$ROMIO_HINTS" ]; then
-  echo "romio_no_indep_rw true"   >$ROMIO_HINTS
-  echo "romio_cb_write enable"   >>$ROMIO_HINTS
-  echo "romio_ds_write enable"   >>$ROMIO_HINTS
-  echo "romio_cb_read enable"    >>$ROMIO_HINTS
-  echo "romio_ds_read enable"    >>$ROMIO_HINTS
-  echo "cb_buffer_size 16777216" >>$ROMIO_HINTS
-  echo "cb_config_list *:1"      >>$ROMIO_HINTS
+striping_factor=256
+striping_unit=67108864
+if [ $nodes -lt 1024 ]; then
+  striping_factor=128
+  striping_unit=16777216
+elif [ $nodes -lt 128 ]; then
+  striping_factor=64
+  striping_unit=16777216
 fi
-
+MPICH_MPIIO_HINTS="*:cray_cb_write_lock_mode=2:cray_cb_nodes_multiplier=4:striping_unit=${striping_unit}:striping_factor=${striping_factor}:romio_cb_write=enable:romio_ds_write=disable:romio_no_indep_rw=true"
 
 # sbatch
 SFILE=s.bin
@@ -82,7 +85,7 @@ echo "#SBATCH --exclusive" >>$SFILE
 echo "#SBATCH --ntasks-per-node=$gpu_per_node" >>$SFILE
 echo "#SBATCH --gpus-per-task=1" >>$SFILE
 echo "#SBATCH --gpu-bind=closest" >>$SFILE
-echo "#SBATCH --cpus-per-task=$cores_per_socket" >>$SFILE
+echo "#SBATCH --cpus-per-task=$cores_per_numa" >>$SFILE
 
 echo "module load PrgEnv-gnu" >> $SFILE
 echo "module load craype-accel-amd-gfx90a" >> $SFILE
@@ -108,7 +111,12 @@ echo "export NEKRS_HOME=$NEKRS_HOME" >>$SFILE
 echo "export NEKRS_GPU_MPI=1 " >>$SFILE
 
 echo "export NVME_HOME=$NVME_HOME" >>$SFILE
-echo "export ROMIO_HINTS=$ROMIO_HINTS" >>$SFILE
+
+if [ $nodes -gt 32 ]; then
+  echo "export MPICH_MPIIO_HINTS=$MPICH_MPIIO_HINTS" >>$SFILE
+  echo "export MPICH_MPIIO_STATS=1" >>$SFILE
+fi
+
 echo "export MPICH_OFI_NIC_POLICY=NUMA" >>$SFILE
 echo "export NEKRS_CACHE_BCAST=$NEKRS_CACHE_BCAST" >> $SFILE
 
@@ -119,16 +127,30 @@ echo "" >> $SFILE
 echo "date" >>$SFILE
 echo "" >> $SFILE
 
+bin_nvme=$NVME_HOME"nekrs-bin"
+bin_nvme_libs=$bin_nvme"_libs"
+echo "sbcast --send-libs -pf $bin $bin_nvme" >> $SFILE
+echo "if [ ! \"\$?\" == \"0\" ]; then"  >> $SFILE
+echo "    echo \"SBCAST failed!\"" >> $SFILE
+echo "    exit 1" >> $SFILE
+echo "fi" >> $SFILE
+
+echo "export LD_LIBRARY_PATH=$bin_nvme_libs:${LD_LIBRARY_PATH}" >> $SFILE
+echo "export LD_PRELOAD=$bin_nvme_libs/libnekrs.so:$bin_nvme_libs/libocca.so:$bin_nvme_libs/libnekrs-hypre-device.so:$bin_nvme_libs/libnekrs-hypre.so" >> $SFILE
+
+echo "ls -ltra $NVME_HOME" >> $SFILE
+echo "ls -ltra $bin_nvme_libs" >> $SFILE
+echo "ldd $bin_nvme" >> $SFILE
+
 if [ $NEKRS_SKIP_BUILD_ONLY -eq 0 ]; then
 echo "# precompilation" >>$SFILE
-echo "srun -N 1 -n 1 $bin --backend $backend --device-id 0 --setup $case --build-only $ntasks" >>$SFILE
+echo "srun -N 1 -n 1 $bin_nvme --backend $backend --device-id 0 --setup $case --build-only $ntasks" >>$SFILE
 fi
 echo "" >> $SFILE
 
 echo "# actual run" >>$SFILE
-echo "srun -N $nodes -n $ntasks $bin --backend $backend --device-id 0 --setup $case" >>$SFILE
+echo "srun -N $nodes -n $ntasks $bin_nvme --backend $backend --device-id 0 --setup $case" >>$SFILE
 
 sbatch $SFILE
 
 # clean-up
-rm -rf $SFILE $ROMIO_HINTS
